# Generated by Django 5.0.2 on 2024-02-13 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('second_name', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=20)),
                ('area', models.CharField(max_length=67)),
            ],
        ),
    ]
